max:
  delegators: 1000
  validators: 500
  full_nodes: 100
  accounts: 10000
  staked_amount: 1000000000
  password: "pablito"
  concurrency: 200
  buffer: 2000

medium:
  delegators: 100
  validators: 50
  full_nodes: 20
  accounts: 1000
  staked_amount: 1000000000
  password: "pablito"
  concurrency: 100
  buffer: 1000

default:
  delegators: 10
  validators: 5
  full_nodes: 2
  accounts: 100
  staked_amount: 1000000000
  password: "pablito"
  concurrency: 100
  buffer: 1000

min:
  delegators: 1
  validators: 1
  full_nodes: 1
  accounts: 10
  staked_amount: 1000000000
  password: "pablito"
  concurrency: 10
  buffer: 100

mature:
  delegators: 500
  validators: 250
  full_nodes: 50
  accounts: 5000
  staked_amount: 1000000000
  password: "pablito"
  concurrency: 150
  buffer: 1500
