default:
  general:
    basePort: 50000
    accounts: 3
    fee: 10001
    chains: [1, 2]
    password: "test"
    incremental: true
    maxHeight: 3
    waitForNewBlock: true
  send:
    chains: [1, 2]
    count: 100 # per block
    amount: 1
    concurrency: 10
  transactions:
    stake:
      - from: 1
        to: 1
        amount: 1000
        committees: [1, 2]
        delegate: true
        height: 1
        earlyWithdrawal: true
        # netAddress: "fake.com"
    # editStake:
    #   - from: 1
    #     amount: 10000
    #     committees: [1, 2]
    #     delegate: true
    #     height: 2
    #     netAddress: "fake.com"
    #     earlyWithdrawal: true
    # pause:
    #   - from: 1
    #     height: 3
    # unstake:
    #   - from: 1
    #     height: 4
    # changeParam:
    #   - from: 1
    #     paramSpace: "fee"
    #     paramKey: "fee"
    #     paramValue: 10001
    #     height: 5
    #     startBlock: 10
    #     endBlock: 100
    # dao-transfer:
    #   - from: 1
    #     to: 2
    #     amount: 1000
    #     height: 6
    #     startBlock: 10
    #     endBlock: 100
    # subsidy:
    #   - from: 1
    #     to: 1
    #     amount: 1000
    #     height: 6
    #     opCode: "test"
    #     committees: [1, 2]

send-bulk:
  general:
    accounts: 3
    fee: 10001
    chainId: 1
    networkId: 1
    password: "test"
    incremental: true
    maxHeight: 101
    waitForNewBlock: true
    notifyNewBlockDelay: 0
  send:
    count: 10000 # per block
    bulk: true
    bulkSplit: 1500
    amount: 1
    concurrency: 100
    usePrivateKey: true
  transactions:

dex:
  general:
    accounts: 3
    fee: 10001
    chainId: 1
    networkId: 1
    password: "test"
    incremental: true
    maxHeight: 3
    waitForNewBlock: true
    notifyNewBlockDelay: 0
  transactions:
    dexLimitOrder:
      - height: 1
        from: 1
        to: 1
        sellAmount: 25
        receiveAmount: 19
        committees: [2]
