default:
  general:
    concurrency: 100
    password: "pablito"
    buffer: 1000
    netAddressSuffix: .p2p
  nodes:
    count: 3
  chains:
    chain_1:
      id: 1
      rootChain: 1
      validators:
        count: 2
        stakedAmount: 1000000000
        amount: 1000000
        committees: [1, 2]
      fullNodes:
        count: 0
        amount: 1000000
      accounts:
        count: 1
        amount: 1000000
      delegators:
        count: 0
        stakedAmount: 1000000000
        amount: 1000000
        committees: [1, 2]
      committees:
        - id: 2
          # must be less than or equal to the number of validators
          # these will be the validator nodes for the nested chain
          count: 1
    # if is a nested chain, these will basically be full nodes because the validator set
    # comes from the root chain
    chain_2:
      id: 2
      rootChain: 1
      validators:
        # could be 0 for no full nodes on a nested chain
        count: 1
        stakedAmount: 1000000000
        amount: 1000000
        committees: [2]
      fullNodes:
        count: 0
        amount: 1000000
      accounts:
        count: 2
        amount: 1000000
      delegators:
        count: 0
        stakedAmount: 1000000000
        amount: 1000000
        committees: [2]
