default:
  general:
    concurrency: 100
    password: "pablito"
    buffer: 1000
    netAddressSuffix: ".p2p"
    jsonBeautify: true
  nodes:
    count: 5
  chains:
    chain_1:
      id: 1
      rootChain: 1
      sleepUntil: 0
      validators:
        count: 3
        stakedAmount: 1000000000
        amount: 1000000
      fullNodes:
        count: 0
        amount: 1000000
      accounts:
        count: 1
        amount: 1000000
      delegators:
        count: 10
        stakedAmount: 100
        amount: 100
      committees:
        - id: 2
          validatorCount: 1
          delegatorCount: 1
    chain_2:
      id: 2
      rootChain: 1
      validators:
        count: 1
        stakedAmount: 1000000000
        amount: 1000000
      fullNodes:
        count: 0
        amount: 1000000
      accounts:
        count: 2
        amount: 1000000
      delegators:
        count: 0
        stakedAmount: 100
        amount: 100
      committees: []

min:
  general:
    concurrency: 10
    password: "pablito"
    buffer: 1000
    netAddressSuffix: ".p2p"
  nodes:
    count: 2
  chains:
    chain_1:
      id: 1
      rootChain: 1
      validators:
        count: 2
        stakedAmount: 1000000000
        amount: 1000000
      fullNodes:
        count: 0
        amount: 1000000
      accounts:
        count: 1
        amount: 1000000
      delegators:
        count: 0
        stakedAmount: 100
        amount: 1000000
      committees: []

medium:
  general:
    concurrency: 100
    password: "pablito"
    buffer: 1000
    netAddressSuffix: ".p2p"
  nodes:
    count: 100
  chains:
    chain_1:
      id: 1
      rootChain: 1
      validators:
        count: 50
        stakedAmount: 1000000000
        amount: 1000000
      fullNodes:
        count: 10
        amount: 1000000
      accounts:
        count: 100
        amount: 1000000
      delegators:
        count: 10
        stakedAmount: 100
        amount: 1000000
      committees:
        - id: 2
          validatorCount: 10
          delegatorCount: 5
    chain_2:
      id: 2
      rootChain: 1
      validators:
        count: 25
        stakedAmount: 1000000000
        amount: 1000000
      fullNodes:
        count: 5
        amount: 1000000
      accounts:
        count: 50
        amount: 1000000
      delegators:
        count: 0
        stakedAmount: 100
        amount: 1000000
      committees: []

max:
  general:
    concurrency: 200
    password: "pablito"
    buffer: 1000
    netAddressSuffix: ".p2p"
  nodes:
    count: 475
  chains:
    chain_1:
      id: 1
      rootChain: 1
      validators:
        count: 200
        stakedAmount: 1000000000
        amount: 1000000
      fullNodes:
        count: 50
        amount: 1000000
      accounts:
        count: 500
        amount: 1000000
      delegators:
        count: 50
        stakedAmount: 100
        amount: 1000000
      committees:
        - id: 2
          validatorCount: 50
          delegatorCount: 20
    chain_2:
      id: 2
      rootChain: 1
      validators:
        count: 150
        stakedAmount: 1000000000
        amount: 1000000
      fullNodes:
        count: 25
        amount: 1000000
      accounts:
        count: 250
        amount: 1000000
      delegators:
        count: 25
        stakedAmount: 100
        amount: 1000000
      committees: []

mature:
  general:
    concurrency: 150
    password: "pablito"
    buffer: 1000
    netAddressSuffix: ".p2p"
  nodes:
    count: 200
  chains:
    chain_1:
      id: 1
      rootChain: 1
      validators:
        count: 150
        stakedAmount: 1000000000
        amount: 1000000
      fullNodes:
        count: 50
        amount: 1000000
      accounts:
        count: 500
        amount: 1000000
      delegators:
        count: 100
        stakedAmount: 100
        amount: 1000000
      committees: []
