- name: Update k3s cluster packages
  hosts: k3s_cluster
  tasks:
    - name: Upgrade package list
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: install python3 and pip
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present
      when: inventory_hostname in groups['server']

    - name: install kubernetes python package system-wide
      ansible.builtin.apt:
        name:
          - python3-kubernetes
        state: present
      when: inventory_hostname in groups['server']
