default:
  general:
    rpcURL: "http://localhost:50002"
    adminRpcURL: "http://localhost:50003"
    basePort: 50000
    accounts: 3
    fee: 10001
    chains: [1, 2]
    password: "pablito"
    incremental: true
    maxHeight: 3
    waitForNewBlock: false
  send:
    chains: [1, 2]
    count: 10 # per block
    amount: 10
    concurrency: 10
  transactions:
    stake:
      - from: 0
        to: 0
        amount: 1000
        committees: [1, 2]
        delegate: true
        height: 1
        netAddress: "tcp://fake.com"
        earlyWithdrawal: true
    # editStake:
    #   - from: 1
    #     to: 2
    #     amount: 1100
    #     committees: [1]
    #     height: 2
    # pause:
    #   - from: 1
    #     to: 2
    #     height: 3
    # unstake:
    #   - from: 1
    #     to: 2
    #     height: 4
    # changeParam:
    #   - from: 1
    #     paramSpace: "fee"
    #     paramKey: "fee"
    #     paramValue: 10001
    #     height: 5
    #     startBlock: 10
    #     endBlock: 100
