apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: canopy-nodes
  namespace: canopy
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: canopy
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      # drop the volatile labels from the scraped metrics (so instance won't split series)
      metricRelabelings:
        - action: labeldrop
          regex: "instance"
